server:
  port: 7070
spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kopaldb
    username: root
    password: manish
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
