spring:
  application:
    name: ELK-STACK-EXAMPLE

server:
  port: 9898

logging:
  file:
    name: D:/spring-boot-logging/elk-stack.log
  level:
    com:  
      manish:
        javadev: DEBUG
        
