server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apigateway
    username: root
    password: manish
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
    
logging:
  file:
    name: D:/spring-boot-logging/elk-stack.log
  level:
    com:  
      manish:
        javadev: DEBUG
    
    
    
    
    